### PR TITLE
add CODEOWNERS

### PR DESCRIPTION
**Pull request by sherluck08**
I added codeowners to the repo

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Reviewing this right now, let's see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Oh looks like the `CODEOWNERS` file I gave you is outdated. It has **Carl listed**, but he's... no longer with the company. Could you **remove him from the file**, but not from our hearts, and push that change?

**Review by sherluck08 — COMMENTED** [review]
I just updated the codeowners

**Comment by sherluck08** [comment]
updated codeowners

**Pull request closed without merging**
